-- Bookshop (inserting data)


INSERT `languages` (`name`) VALUES
('English'),
('Mandarin Chinese'),
('Hindi'),
('Spanish'),
('Standard Arabic'),
('Bengali'),
('French'),
('Russian'),
('Portuguese'),
('Urdu'),
('Indonesian'),
('Standard German'),
('Japanese'),
('Marathi'),
('Telugu'),
('Turkish'),
('Tamil'),
('Yue Chinese'),
('Wu Chinese');


INSERT `book_genres` (`name`) VALUES
('Fantasy'),
('Adventure'),
('Romance'),
('Contemporary'),
('Dystopian'),
('Mystery'),
('Horror'),
('Thriller'),
('Paranormal'),
('Historical fiction'),
('Science Fiction'),
('Memoir'),
('Cooking'),
('Art'),
('Self-help / Personal'),
('Development'),
('Motivational'),
('Health'),
('History'),
('Travel'),
('Guide / How-to'),
('Families & Relationships'),
('Humor'),
('Children’s');


INSERT `categories` (`name`) VALUES
('Antiques & Collectibles'),
('Architecture'),
('Art'),
('Bibles'),
('Biography & Autobiography'),
('Body, Mind & Spirit'),
('Business & Economics'),
('Comics & Graphic Novels'),
('Computers'),
('Cooking'),
('Crafts & Hobbies'),
('Design'),
('Drama'),
('Education'),
('Family & Relationships'),
('Fiction'),
('Foreign Language Study'),
('Games & Activities'),
('Gardening'),
('Health & Fitness'),
('History'),
('House & Home'),
('Humor'),
('Juvenile Fiction'),
('Juvenile Nonfiction'),
('Language Arts & Disciplines'),
('Law'),
('Literary Collections'),
('Literary Criticism'),
('Mathematics'),
('Medical'),
('Music'),
('Nature'),
('Performing Arts'),
('Pets'),
('Philosophy'),
('Photography'),
('Poetry'),
('Political Science'),
('Psychology'),
('Reference'),
('Religion'),
('Science'),
('Self-help'),
('Social Science'),
('Sports & Recreation'),
('Study Aids'),
('Technology & Engineering'),
('Transportation'),
('Travel'),
('True Crime'),
('Young Adult Fiction'),
('Young Adult Nonfiction');


INSERT `order_statuses` (`name`) VALUES
(`Pending`),
(`Processing`),
(`On hold`),
(`Completed`),
(`Cancelled`),
(`Refunded`),
(`Failed`),
(`In Packaging`);


