INSERT `authors` (`id`, `firstname`, `lastname`, `about`) VALUES
(1, 'Nichole', 'Perkins', 'Nichole Perkins is a writer from Nashville, Tennessee. She is a 2016 Callaloo Creative Writing Fellow in poetry, the Audre Lorde Fellow at the 2017 Jack Jones Literary Arts Retreat, and a 2017 BuzzFeed Emerging Writers Fellow. Nichole enjoys too much pop culture and chocolate.'),
(2, 'Leila', 'Slimani', DEFAULT),
(3, 'André', 'Aciman', 'ANDRÉ ACIMAN is the author of Eight White Nights, Call Me by Your Name, Out of Egypt, False Papers, Alibis, Harvard Square, and Enigma Variations, and is the editor of The Proust Project. He teaches comparative literature at the Graduate Center of the City University of New York. He lives with his wife in Manhattan.'),
(4, 'George', 'Orwell', 'George Orwell, the pseudonym of Eric Arthur Blair, was born in Bengal, India, in 1903. He was educated at Eton, became a policeman in Burma but suffered and studied poverty. His great works, Animal Farm and Nineteen Eighty-Four, are a product of his hatred of totalitarianism. His legacy of writing and political thought is much admired today.'),
(5, 'Erich', 'Fromm', 'Erich Fromm (1900-1980) emigrated from Germany in 1934 to the United States, where he held a private psychotherapeutic practice and taught at Columbia, Yale, and New York University. His many books include The Art of Loving, Escape from Freedom, Man for Himself, and The Anatomy of Human Destructiveness.'),
(6, 'Michael', 'Crichton', 'Michael Crichton (1942-2008) was the author of the bestselling novels The Terminal Man, The Great Train Robbery, Jurassic Park, Sphere, Disclosure, Prey, State of Fear, Next and Dragon Teeth, among many others. His books have sold more than 200 million copies worldwide, have been translated into forty languages, and have provided the basis for fifteen feature films. He wrote and directed Westworld, The Great Train Robbery, Runaway, Looker, Coma and created the hit television series ER. Crichton remains the only writer to have a number one book, movie, and TV show in the same year.'),
(7, 'John', 'Mueller', DEFAULT),
(8, 'China', 'Miéville', 'China Mieville has a Ph.D. from the London School of Economics. He lives in England. He is the author of several books, including King Rat, which was nominated for both the International Horror Guild and Bram Stoker Awards for best first novel, and Perdido Street Station, winner of the 2001 Arthur C. Clarke Award.'),
(9, 'Doris', 'Pena-Cruz', DEFAULT),
(10, 'David', 'Kim', 'David Hoon Kim is a Korean-born American educated in France, who took his first creative writing workshop at the Sorbonne before attending the Iowa Writers\' Workshop and the Stegner Program. His fiction has appeared in The New Yorker, Brins d\'éternité, Le Sabord and XYZ La revue de la nouvelle. He has been awarded fellowships from the Fine Arts Work Center in Provincetown, the Michener-Copernicus Society of America, the MacDowell Colony, the Elizabeth George Foundation, among others. Paris Is a Party, Paris Is a Ghost is his first book. He writes in English and in French.'),
(11, 'Stephen', 'King', DEFAULT),
(12, 'Eugene', 'Petrov', DEFAULT),
(13, 'Ilya', 'Ilf', DEFAULT);