INSERT `book_genres` (`id`, `name`) VALUES
(1, 'Fantasy'),
(2, 'Adventure'),
(3, 'Romance'),
(4, 'Contemporary'),
(5, 'Dystopian'),
(6, 'Mystery'),
(7, 'Horror'),
(8, 'Thriller'),
(9, 'Paranormal'),
(10, 'Historical fiction'),
(11, 'Science fiction'),
(12, 'Memoir'),
(13, 'Cooking'),
(14, 'Art'),
(15, 'Self help / Personal'),
(16, 'Development'),
(17, 'Motivational'),
(18, 'Health'),
(19, 'History'),
(20, 'Travel'),
(21, 'Guide / How-to'),
(22, 'Families & Relationships'),
(23, 'Humor'),
(24, 'Utopia'),
(25, 'Realism'),
(26, 'Children’s');