INSERT `languages` (`id`, `name`) VALUES
(1, 'English'),
(2, 'Mandarin Chinese'),
(3, 'Hindi'),
(4, 'Spanish'),
(5, 'Standard Arabic'),
(6, 'Bengali'),
(7, 'French'),
(8, 'Russian'),
(9, 'Portuguese'),
(10, 'Urdu'),
(11, 'Indonesian'),
(12, 'Standard German'),
(13, 'Japanese'),
(14, 'Marathi'),
(15, 'Telugu'),
(16, 'Turkish'),
(17, 'Tamil'),
(18, 'Yue Chinese'),
(19, 'Wu Chinese');